# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genproto/transaction/transaction_api.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'genproto/transaction/transaction_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*genproto/transaction/transaction_api.proto\x12\x0btransaction\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x01\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x1c.transaction.TransactionType\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x0e\n\x06sender\x18\x04 \x01(\t\x12\x10\n\x08receiver\x18\x05 \x01(\t\x12-\n\ttimestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1f\n\x04user\x18\x08 \x01(\x0b\x32\x11.transaction.User\"\xa8\x01\n\x13TransactionResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x1c.transaction.TransactionType\x12)\n\toperation\x18\x03 \x01(\x0e\x32\x16.transaction.Operation\x12.\n\x06status\x18\x04 \x01(\x0e\x32\x1e.transaction.TransactionStatus\"N\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t*l\n\x0fTransactionType\x12 \n\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17TRANSACTION_TYPE_CREDIT\x10\x01\x12\x1a\n\x16TRANSACTION_TYPE_DEBIT\x10\x02*<\n\tOperation\x12\x19\n\x15OPERATION_UNSPECIFIED\x10\x00\x12\x14\n\x10OPERATION_INSERT\x10\x01*w\n\x11TransactionStatus\x12\"\n\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n\x1aTRANSACTION_STATUS_SUCCESS\x10\x01\x12\x1e\n\x1aTRANSACTION_STATUS_FAILURE\x10\x02\x32\x61\n\x0eTransactionAPI\x12O\n\x11InsertTransaction\x12\x18.transaction.Transaction\x1a .transaction.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genproto.transaction.transaction_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONTYPE']._serialized_start=545
  _globals['_TRANSACTIONTYPE']._serialized_end=653
  _globals['_OPERATION']._serialized_start=655
  _globals['_OPERATION']._serialized_end=715
  _globals['_TRANSACTIONSTATUS']._serialized_start=717
  _globals['_TRANSACTIONSTATUS']._serialized_end=836
  _globals['_TRANSACTION']._serialized_start=93
  _globals['_TRANSACTION']._serialized_end=292
  _globals['_TRANSACTIONRESPONSE']._serialized_start=295
  _globals['_TRANSACTIONRESPONSE']._serialized_end=463
  _globals['_USER']._serialized_start=465
  _globals['_USER']._serialized_end=543
  _globals['_TRANSACTIONAPI']._serialized_start=838
  _globals['_TRANSACTIONAPI']._serialized_end=935
# @@protoc_insertion_point(module_scope)
